spring:
  application:
    name: hanaro

  config:
    import: classpath:security.yml

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
        time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always

  servlet:
    multipart:
      location: src/main/resources/static/tmp
      max-request-size: 10MB
      max-file-size: 2MB

upload:
  path: E:/workspace/hana8/hanaro/hanaro/src/main/resources/static/upload

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: health,metrics,env,beans
  endpoint:
    metrics:
      access: read_only
    health:
      show-details: always

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  api-docs:
    enabled: true
    path: /v3/api-docs
